- internal/auth/jwt.go
- internal/database/database.go
Add a new ENV var named `COOKIE_DOMAIN`. This helpful when deploying Ganymede behind a reverse proxy using different subdomains for each service. Setting the `COOKIE_DOMAIN` to the root subdomain for Ganymede will solve the cookie issues.
Add support for database SSL root certs. Valid options for `DB_SSL` include:
- disable - No SSL
- require - Always SSL (skip verification)
- verify-ca - Always SSL (verify that the certificate presented by the server was signed by a trusted CA)
- verify-full - Always SSL (verify that the certification presented by the server was signed by a trusted CA and the server host name matches the one in the certificate)
If `DB_SSL` is *not* set to disable, then the ENV var `DB_SSL_ROOT_CERT` needs to point to a DB ssl root cert.
> Cookie and DB SSL

- internal/archive/archive.go
When live archiving with the chat option disabled, the post-process of the live video would fail. This is because it attempted to kill the chat downloader when it wasn't running. Added a check to see if the chat download task is not complete.
> fix(archive): continue live video post-process if no chat

- internal/live/live.go
- internal/transport/http/handler.go
- internal/transport/http/live.go
- internal/utils/chat.go
Twitch Downloader v1.50.4 broke the Live VOD chat to VOD chat conversion function. This PR changes the following:
- Badge version is now saved as a string (was an int).
- Empty emoticon fragments are now `null` rather than `{ "emoticon_id": "", "emoticon_set_id": "" }`
Also added a `chat-conversion` HTTP endpoint for rapid testing the conversion function.
These are all the issues I found immediately. I will merge this request and perform more tests from master.
> Changes for Twitch Downloader v1.50.4

- internal/config/config.go
- internal/exec/exec.go
- internal/transport/http/config.go
For https://github.com/Zibbp/ganymede/issues/57
This PR add a new entry in `config.json` named `streamlink_live`. This allows the modification of Streamlink arguments **only** for live streams / live archives by the user.
The `DownloadTwitchLiveVideo` exec function now reads those arguments and uses them.
> fix(streamlink): Twitch Embedded Ads

- internal/archive/archive.go
- internal/config/config.go
- internal/exec/exec.go
- internal/transport/http/config.go
- internal/utils/file.go
This PR adds support for a "convert to HLS" feature. It is disabled by default and can be enabled at Admin > Settings. When enabled, during the "video conversion" queue job, the mp4 file will be converted to an HLS playlist. Serving a segmented video such as HLS is more efficient that large video files.
> feat(archive): HLS support

- ent/live.go
- ent/live/live.go
- ent/live/where.go
- ent/live_create.go
- ent/live_update.go
- ent/migrate/schema.go
- ent/mutation.go
- ent/queue.go
- ent/queue/queue.go
- ent/queue/where.go
- ent/queue_create.go
- ent/queue_update.go
- ent/runtime.go
- ent/schema/live.go
- ent/schema/queue.go
- internal/archive/archive.go
- internal/live/live.go
- internal/live/vod.go
- internal/transport/http/archive.go
- internal/transport/http/live.go
This PR adds support for a "render chat" option. Some users may not want to chat rendered and this gives them the ability to disable that. The option is a slider next to the "archive chat" slider on the archive page and the watched channels page.
> "Render Chat" Options

- ent/live.go
- ent/live/live.go
- ent/live/where.go
- ent/live_create.go
- ent/live_update.go
- ent/migrate/schema.go
- ent/mutation.go
- ent/runtime.go
- ent/schema/live.go
- internal/live/live.go
- internal/live/vod.go
- internal/transport/http/handler.go
- internal/transport/http/live.go
- internal/transport/http/twitch.go
- internal/twitch/gql.go
Adds the ability to enable or disable downloading subscriber-only videos when watching a channel for new videos. 
Twitch's Helix API does not expose the information whether a video has a sub-only restriction or not. I am using Twitch's undocumented GraphQL API to perform the check. The check occurs near the end of the "CheckVodWatchedChannels" function when it has been determined the video ID is new and not already archived. The graphql request is made and the response is checked to determine if a sub-only restriction is enabled. If so, and the "download sub only" option is disabled, the video is skipped. If not, the Twitch token is checked to ensure it is set then the video is sent to the queue.
> Watched channels subscriber only videos

- Dockerfile.aarch64
After the last changes from https://github.com/Zibbp/ganymede/pull/158 there was an error for su-exec because is was not found.
It seems that su-exec is not available in the normal apt-get repository for debain/ubunut.
So i add support to build it from source https://github.com/ncopa/su-exec.
After these changes PUID= and PGID= is working flawless and the container starts up normally again.
> fix Dockerfile.aarch64

- .devcontainer/devcontainer.json
- docs/docs.go
- docs/swagger.json
- docs/swagger.yaml
- go.mod
- go.sum
- internal/transport/http/vod.go
- internal/vod/vod.go
This PR supports deleting vod files **only**. Closes https://github.com/Zibbp/ganymede/issues/184
- when deleting a vod, there is now a "switch" to enable deleting the vod folder/files. 
- the "vod menu" has a delete item for admins
> feat(vod): support deleting files

- internal/archive/archive.go
- internal/live/live.go
Add a check to see if a livestream with the same ID is A) archiving and B) is downloading the video. If both are true than do not add the livestream to the queue.
> Fix live archive check creating duplicate archive

- internal/config/config.go
- internal/scheduler/scheduler.go
- Add a config option named `video_check_interval_minutes`. This allows the user to configure the interval in which channels are checked for videos to archive.
- Defaults to 3 hours.
> feat: video schedule interval

- internal/archive/archive.go
Hopefully fixes #257 
A stream may have ended but the Twitch API hasn't updated yet. This causes a new archive to be created. When the first task runs (save livestream info) the Twitch API finally updates. This causes the task to fail as there is no stream data. This PR checks if there is stream data. If there isn't any data, the queue is stopped and deleted, along with the video.
> fix(archive): return and delete queue if no stream data

- internal/activities/video.go
Fixes https://github.com/Zibbp/ganymede/issues/346
> feat(activity/livevideo): attempt to update livestream archive with the external vod id

- internal/activities/video.go
Resolves https://github.com/Zibbp/ganymede/issues/437
> feat(activities): handle and kill multiple chat process ids

- internal/utils/tdl.go
TwitchDownloader 1.54.6 relaxed the requirements on rendering highlighted messages, so I figured Ganymede could support marking message as highlighted.
I hope this solution is alright, it's my first time writing any Go code. Please let me know if any changes are needed.
> Mark highlighted messages as highlighted when converting to TDL

- internal/utils/tdl.go
This is related to issues #413 and #437. I also experienced this issue with emotes getting parsed incorrectly, leading to a live-chat that would fail to convert.
In my instance, the conversion from a live chat would fail with `runtime error: slice bounds out of range` and would hang with no further status updates in the queue. 
The message that caused the error is as follows: `"You Fooool" LUL LUL LUL` which is `\u201cYou Fooool\u201d LUL LUL LUL` as the quotation marks are unicode characters. I noticed that in the `emoteFragments` splice in `ganymede/internal/utils/tdl.go`, two of the three LUL emotes had duplicate `pos1` and `pos2` values, despite there being three "LUL" emotes in three different positions.
In the original live chat file, each LUL had the following positions, …
> Potential fix for incorrectly parsed emotes when a message is offset due to unicode characters.

- .devcontainer/devcontainer.json
- Makefile
- cmd/worker/main.go
- docker-compose.yml
- internal/database/database.go
- internal/server/server.go
Re-add the ability to specify the `DB_SSL_ROOT_CERT` variable which is a path to a SSL certificate used to secure the postgres connection.
> feat: re-add database ssl support

- frontend/app/components/admin/watched/DrawerContent.tsx
- frontend/app/hooks/useWatchedChannels.ts
- internal/live/live.go
- internal/transport/http/live.go
Fixes https://github.com/Zibbp/ganymede/issues/554
Rename `max_age` to `video_age` to match what the database is. Also default to `0` to archive all videos.
> fix: max video age for watched channels

- frontend/app/admin/settings/page.tsx
- frontend/app/layout.tsx
This fixes a bug where environment variables were not properly being passed to the browser so the client-side javascript can use them.
> fix(frontend): make env vars available in browser

- internal/platform/twitch_api.go
```
9:34PM WRN Rate limit usage is over 75% - 15/800 remaining rate_limit=800 rate_limit_expires="2025-01-22 21:34:43 -0600 CST" rate_limit_remaining=15
```
In my tests the rate limit never got below 799/800. From what I can tell Twitch is very generous with API limits.
> feat(platform/twitch): log warning if ratelimit exceeds threshold

- frontend/app/components/landing/RecentlyArchived.tsx
- frontend/app/profile/page.tsx
- frontend/app/store/useSettingsStore.ts
Instead of hard coding it in https://github.com/Zibbp/ganymede/pull/606 add a setting to allow users to toggle this in their profile settings.
Original issue - https://github.com/Zibbp/ganymede/issues/598
> feat(frontend): add settings to display processing video in recently archived

- internal/vod/vod.go
Resolved https://github.com/Zibbp/ganymede/issues/342 where if one of FirstParty or ThirdParty lists are empty it should not use any of them. Some changes might only have first party emotes.
> fix(vod): use or statement when checking for embedded images

- frontend/app/components/videos/ChatMessage.tsx
- frontend/app/components/videos/ChatPlayer.tsx
Fixes the edge case in #669 where a comment's offset is a whole number which may get processed multiple times if the start/end times of fetching the next batch of comments aligns with the comment's offset. Comment IDs are kept in a variable and checked before appending to the chat.
> fix(frontend/chatplayer): track processed chat ids to prevent duplicates

- frontend/app/layout/Navbar.tsx
https://github.com/Zibbp/ganymede/issues/679 - prevent performing the action unless the query has content. Also add search bar to the mobile drawer.
> Navbar search fix

- internal/tasks/common.go
https://github.com/Zibbp/ganymede/issues/725
Twitched decided to (mistakenly?) require authentication for their sprite thumnails. This is causing the thumbnail download task to fail. This is also affecting the official Twitch website 🙃. Ganymede generates better quality sprite thumbnails anyway so remove this logic entirely.
> fix(tasks): remove fetching sprite thumbnails for twitch

- frontend/messages/de.json
- frontend/messages/en.json
Also contains two typo fixes for `en`
> Extend german translations

- frontend/app/search/page.tsx
- internal/chapter/chapter.go
- internal/chat/ffz.go
- internal/chat/seventv.go
- internal/exec/exec.go
- internal/exec/thumbnails.go
- internal/live/live.go
- internal/notification/notification.go
- internal/platform/twitch_api.go
- internal/platform/twitch_gql.go
- internal/server/server.go
- internal/tasks/video.go
- internal/twitch/graphql.go
- internal/twitch/twitch.go
- internal/utils/file.go
- internal/utils/live_chat.go
- internal/worker/worker.go
- Every time the live stream channel check runs, check all live streams and update the chapters if necessary. This means live streams (through watched channels only) will have chapters (categories).
- Update file close defer functions to debug instead of error
> feat(live): update chapters for live streams during live stream check

- frontend/translation-coverage.js
- add colored output (if tty is attached to stdout)
- list missing translations per locale
- list extra translations, that are not present in base locale
Example output against current `main` branch:
Example output when everything is okay:
> Extend frontend/translation-coverage.js

- frontend/messages/de.json
- add new translations for changes made in #735
- move misplaced translation key from `QueuePage.column.modal.cancel` to `QueuePage.modal.cancel`
- update some existing translations to relect the context they are used in better
- fix some minor typos
With this the german translation is back to 100%
> Update german frontend translations

- frontend/app/components/authentication/ForceLogin.tsx
Returning `null` worked fine in dev mode. When built and deployed it messed up hydration. Return an empty div instead.
> force login fixes

- internal/live/live.go
- internal/tasks/shared.go
This PR fixes a critical bug in the `Check()` function in `internal/live/live.go` that caused the function to exit prematurely when encountering a channel that is already being archived. The bug resulted in only the first live channel being checked and subsequent channels being skipped entirely.
Fixes Zibbp/ganymede#790
Previously, the code at lines [L317-L322](https://github.com/Zibbp/ganymede/blob/main/internal/live/live.go#L317-L322) returned early upon detecting that a stream was already being archived:
```go
if queueItem.Edges.Vod.ExtID == stream.ID && queueItem.TaskVideoDownload == utils.Running {
log.Debug().Msgf("%s is already being archived", lwc.Edges.Channel.Name)
return nil  // ❌ Exits the entire Check() function
}
```
This caused the `Check()` function to skip all remaining …
> Fix early return in Check() that skips other live channels

- internal/live/live.go
- internal/platform/interfaces.go
- internal/platform/twitch.go
- internal/platform/twitch_gql.go
- internal/twitch/graphql.go
- internal/utils/http.go
#760
The Twitch API can be very slow to update when a stream ends. This causes a disconnect between the API and the actual m3u8 stream. Implement a check to see if the m3u8 playlist returns a 200 response (channel is live).
> feat: additional 'is live' check

- internal/vod/vod.go
Fixes https://github.com/Zibbp/ganymede/issues/802
- Fix bug with HLS videos where the base path was being calculated within the HLS subdir
- Add a safety check to ensure the directory being recursively deleted contains the video `folder_name`. If it does not the delete does not proceed
> fix(vod): use video hls path when deleting vods if hls video

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- Dockerfile
[7.5.0](https://github.com/streamlink/streamlink/releases/tag/7.5.0) forces filtering out ads which is unacceptable for Ganymede. Forcing ads to be filtered out causes a disconnect between video timestamps and chat timestamps.
I will likely be moving to yt-dlp in the future.
> fix: pin streamlink to 7.4.0

- frontend/app/admin/settings/page.tsx
- internal/archive/archive.go
- internal/archive/archive_test.go
- internal/archive/utils.go
- internal/archive/utils_test.go
- internal/live/live_test.go
https://github.com/Zibbp/ganymede/issues/832
Add the following new storage template variables:
- `{{YYYY}}`
- `{{MM}}`
- `{{DD}}`
- `{{HH}}`
> feat: add granular date variables for storage templates

- internal/archive/archive_test.go
- internal/live/live.go
- internal/live/live_test.go
- internal/platform/twitch.go
- internal/playlist/rule_test.go
- internal/tasks/periodic/process.go
- internal/tasks/video.go
- internal/utils/enum.go
https://github.com/Zibbp/ganymede/issues/865
A video can have no chapters but usually has a category/game. If no chapters are returned from the platform API then use the video category/game as the only chapter. 
This can be backfilled by running the "Save Chapters for Videos", assuming the videos are still on Twitch.
> feat(archive): create fallback chapter from video category/game if no chapters exist
